# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Logan's Notes
email: logan@protiumit.com
description: > # this means to ignore newlines until "baseurl:"
  Various notes about Openstack, Ceph, and Internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://logan2211.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  logan2211

# Build settings
markdown: kramdown
